server:
  port: 8082

spring:
  application:
    name: products
  datasource:
    url: jdbc:mysql://localhost:3306/superagames?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-adress: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
      fetch-registry: true
      register-with-eureka: true
