server:
  port: 8082

spring:
  application:
    name: products
  datasource:
    url: jdbc:h2:mem:~/superagames
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  flyway:
    table: products_flyway_schema_history
    baseline-on-migrate: true
  h2:
    console:
      path: /h2

eureka:
  instance:
    prefer-ip-adress: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
      register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
