server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:~/superagames
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2

eureka:
  instance:
    prefer-ip-adress: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
      fetch-registry: true
      register-with-eureka: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS