server:
  port: 8084

spring:
  application:
    name: monitor
  datasource:
    url: jdbc:h2:mem:~/superagames
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    table: monitor_flyway_schema_history
    baseline-on-migrate: true
  h2:
    console:
      path: /h2

eureka:
  instance:
    prefer-ip-adress: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
      register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS